# Generated by Django 3.0.3 on 2020-02-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_addfaculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFaculty_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=10)),
                ('addr', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='AddFaculty',
        ),
    ]
