# Generated by Django 3.0.3 on 2020-02-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20200220_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addfaculty_model',
            old_name='fname',
            new_name='fullname',
        ),
        migrations.AlterField(
            model_name='addfaculty_model',
            name='addr',
            field=models.TextField(default='DataFlair Address'),
        ),
        migrations.AlterField(
            model_name='addfaculty_model',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='addfaculty_model',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
