# Generated by Django 3.0.3 on 2020-02-25 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_auto_20200222_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internal_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cns', models.IntegerField()),
                ('uml', models.IntegerField()),
                ('mc', models.IntegerField()),
                ('stm', models.IntegerField()),
                ('hbd', models.IntegerField()),
                ('attendance', models.IntegerField()),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.AddStudent_Model')),
            ],
        ),
    ]
